package:
  create:
    set:
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/embeddings"
      image_version: 0.2.0
      name: embeddings
    max_package_size: "1000000000"
  deploy:
    set:
      name: embeddings
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/embeddings"
      image_version: 0.2.0